name: 自动签到岸云数据

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *' # 每天一次，UTC 时间晚上 10 点运行（即北京时间早上 6 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 从文件读取需要签到的ID
      run: |
        sudo apt-get install -y jq
        uid_list=$(jq -r '.anvps.[]' sign.json)
        for uid in $uid_list; do
          echo "即将签到用户: $uid"
          response=$(curl -s -X POST -d "uid=${uid}" "https://www.anvps.cn/addons?_plugin=sign_in&_controller=index&_action=index")
          msg=$(echo "$response" | jq -r '.msg')
          echo "用户 $uid : $msg"
        done
