name: 自动签到量芯云虚拟主机

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *' # 每天一次，UTC 时间晚上 10 点运行（即北京时间早上 6 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 量芯云虚拟主机签到
      env:
        LXVH_USERPASSWD: ${{ secrets.LXVH_USERPASSWD }}
      run: |
        sudo apt install jq -y 

        IFS=',' read -r -a up <<< "$LXVH_USERPASSWD"

        for item in "${up[@]}"; do  
          IFS=':' read -r user password pid <<< "$item"  
          echo "正在签到前两位为用户名：${user:0:2}"

          curl -c "ck.lx" -X POST "https://idc.prolzy.com/login" -d "username=$user&password=$password&country_id=37&login_type=PASS&submit=1" > /dev/null
          curl -b "ck.lx" -X POST "https://idc.prolzy.com/vhost/detail/$pid/renew" -d "month=1&coupon_id=0&submit=1" | jq ".msg"
          rm -rf ck.lx
        done
