name: 自动续费灰狼云

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 22 * * *' # 每天一次，UTC 时间晚上 10 点运行（即北京时间早上 6 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 灰狼云虚拟主机续费
      env:
        YUN316_USERPASSWD: ${{ secrets.YUN316_USERPASSWD }}
      run: |
        sudo apt install jq -y 

        IFS=',' read -r -a up <<< "$YUN316_USERPASSWD"

        for item in "${up[@]}"; do  
          IFS=':' read -r email password pid <<< "$item"  
          echo "正在签到前两位为邮箱：${email:0:2}"

          curl -s -c "ck.yun316" -X POST "https://www.yun316.net/data/user.php?act=login" -d "email=$email&password=$password&remember=on" > /dev/null
          curl -s -b "ck.yun316" -X POST "https://www.yun316.net/data/host.php?act=renew&id=$pid" -d "planid=$pid&m=1" | jq ".msg"
          rm -rf ck.yun316
        done
